# config.yaml.default (Safe to upload to your public GitHub)
token: "YOUR_LICHESS_API_TOKEN_HERE" # Do not put your real token here

engine:
  name: "stockfish"
  uci_options:
    Threads: 2
    Hash: 1028
    Skill Level: 20

time_control:
  depth: 18

online_moves:
  lichess_cloud_analysis: true
  lichess_bot_tbs:
    syzygy: true
