services:
  - type: web
    name: Studyloversz-bot 
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: LICHESS_TOKEN
        scope: project
      - key: PORT
        value: "8080"
    region: oregon
