services:
  - type: web
    name: Invictus-Knight-Bot
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: LICHESS_TOKEN
        scope: project
      - key: PORT
        value: "8080"
    region: oregon
